apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: ksh-devops-demo

  labels:
    app.kubernetes.io/name: ksh-devops-demo
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: ksh-devops-project

spec:
  replicas: 1

  revisionHistoryLimit: 5

  rollbackWindow:
    revisions: 3

  selector:
    matchLabels:
      app.kubernetes.io/name: ksh-devops-demo

  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ksh-devops-demo

    scaleDown: progressively

  strategy:
    canary:
      stableService: ksh-devops-demo-stable
      canaryService: ksh-devops-demo-canary

      maxUnavailable: 0
      maxSurge: 25%

      trafficRouting:
        istio:
          virtualService:
            name: ksh-devops-demo

            routes:
              - primary

      steps:
        - setWeight: 10

        - analysis:
            templates:
              - templateName: ksh-devops-demo-canary-analysis

            args:
              - name: service-name
                value: >-
                  ksh-devops-demo-canary.ksh-devops-demo.svc.cluster.local

        - setWeight: 50

        - analysis:
            templates:
              - templateName: ksh-devops-demo-canary-analysis

            args:
              - name: service-name
                value: >-
                  ksh-devops-demo-canary.ksh-devops-demo.svc.cluster.local

        - setWeight: 100