apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksh-devops-demo

resources:
  - namespace.yaml
  - ../../base
  - gateway.yaml
  - virtualservice.yaml
  - analysis-template.yaml

patches:
  - path: deployment-patch.yaml
  - path: rollout-patch.yaml

images:
  - name: ksh-devops-demo
    newName: 985704340726.dkr.ecr.ap-northeast-2.amazonaws.com/ksh-devops-demo
    newTag: sha-ef9a6464d1c2-run-37578981364-1